default:
	gcc -c /users/sullypalaia/downloads/programs/scramblealgors/funcs/makeres.c
	gcc -c /users/sullypalaia/downloads/programs/scramblealgors/funcs/algor0.c
	gcc -c /users/sullypalaia/downloads/programs/scramblealgors/funcs/algor1.c
	gcc -c /users/sullypalaia/downloads/programs/scramblealgors/main/main.c
	gcc makeres.o algor0.o algor1.o main.o -o main
	#The preprocessing is done. now execute the main file with desired parameters.
	#Execute the main file with a parameter of help if you need a list of arguments included in this program.